name: teil_tools
publish_to: none
repository: https://github.com/voll-labs/teil_tools

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  melos: ^3.0.0
  teil_lints:
    path: packages/teil_lints
    version: ^0.0.4
